# Generated by Django 4.0.5 on 2022-07-16 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cartapp', '0003_cartitem_ordered'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('oid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=40)),
                ('addr', models.TextField(max_length=100)),
                ('town', models.CharField(max_length=20)),
                ('zipcode', models.SmallIntegerField()),
                ('ph', models.CharField(max_length=15)),
                ('comment', models.TextField(max_length=200)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered')], max_length=30)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartapp.cartitem')),
            ],
        ),
    ]
