# Generated by Django 4.0.5 on 2022-07-16 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mPOSAppv2', '0002_t_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_category',
            fields=[
                ('catid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('catactive', models.IntegerField(max_length=50)),
                ('catname', models.CharField(max_length=100)),
            ],
        ),
    ]
