# Generated by Django 4.0.6 on 2022-08-14 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mPOSAppv2', '0004_alter_t_category_catactive'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_item_setup',
            fields=[
                ('itemid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('catid', models.IntegerField(max_length=30)),
                ('itemactive', models.CharField(max_length=50)),
                ('itemnae', models.CharField(max_length=100)),
            ],
        ),
    ]
