# Generated by Django 4.0.5 on 2022-07-15 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='qty',
            field=models.SmallIntegerField(default=0),
        ),
    ]
