# Generated by Django 4.0.5 on 2022-06-19 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='email',
            fields=[
                ('emailid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('username', models.CharField(default='NA', max_length=25, unique=True)),
                ('subject', models.CharField(max_length=50)),
                ('messagebody', models.CharField(max_length=500)),
            ],
        ),
    ]
