# Generated by Django 4.0.6 on 2022-09-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sa_company', models.IntegerField(default=1, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='sa_lookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sa_company', models.IntegerField(default=1, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='sa_lookupdtl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sa_company', models.IntegerField(default=1, max_length=30)),
            ],
        ),
    ]
