# Generated by Django 4.0.6 on 2022-09-11 18:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('personal_reg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sa_company', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='personal',
            name='sa_company',
        ),
        migrations.AlterField(
            model_name='sa_lookup',
            name='sa_company',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='sa_lookupdtl',
            name='sa_company',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='personal',
            name='position',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='personal_reg.position'),
            preserve_default=False,
        ),
    ]
