# Generated by Django 4.0.6 on 2022-09-11 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_reg', '0002_personal_info_position_remove_personal_sa_company_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Personal_info',
        ),
        migrations.DeleteModel(
            name='sa_lookup',
        ),
        migrations.DeleteModel(
            name='sa_lookupdtl',
        ),
    ]
